define([], function() {
    return {
        alpha: {
            A: 'Allah',
            B: 'Be or Born',
            C: 'Cee (See)',
            D: 'Divine',
            E: 'Equality',
            F: 'Father',
            G: 'God',
            H: 'He or Her',
            I: 'I or Islam',
            J: 'Justice',
            K: 'King or Kingdom',
            L: 'Love, Hell or Right',
            M: 'Master',
            N: 'In or Now Nation',
            O: 'Cypher',
            P: 'Power',
            Q: 'Queen',
            R: 'Rule or Ruler',
            S: 'Self or Savior',
            T: 'Truth or Square',
            U: 'You, Universe, and U-N-I-Verse',
            V: 'Victory',
            W: 'Wisdom',
            X: 'Unknown',
            Y: 'Why',
            Z: 'Zig-Zag-Zig'
        },
        numerics: {
            1: 'Knowledge',
            2: 'Wisdom',
            3: 'Understanding',
            4: 'Culture and Freedom',
            5: 'Power and Refinement',
            6: 'Equality',
            7: 'God',
            8: 'Build and Destroy',
            9: 'Born',
            0: 'Cipher'
        },
        alphanumerics: {
            A: 'Allah',
            B: 'Be or Born',
            C: 'Cee (See)',
            D: 'Divine',
            E: 'Equality',
            F: 'Father',
            G: 'God',
            H: 'He or Her',
            I: 'I or Islam',
            J: 'Justice',
            K: 'King or Kingdom',
            L: 'Love, Hell or Right',
            M: 'Master',
            N: 'In or Now Nation',
            O: 'Cypher',
            P: 'Power',
            Q: 'Queen',
            R: 'Rule or Ruler',
            S: 'Self or Savior',
            T: 'Truth or Square',
            U: 'You, Universe, and U-N-I-Verse',
            V: 'Victory',
            W: 'Wisdom',
            X: 'Unknown',
            Y: 'Why',
            Z: 'Zig-Zag-Zig',
            1: 'Knowledge',
            2: 'Wisdom',
            3: 'Understanding',
            4: 'Culture and Freedom',
            5: 'Power and Refinement',
            6: 'Equality',
            7: 'God: God is the original Asiatic Blackman, the Blackman is God, a wiseman\'s equality born to build or destroy infinity. I, is self, self is the true reality, Son of Man, God Allah.',
            8: 'Build and Destroy: Build means to add on to life a positive creation or education; destroy means to know of, take, that which is untrue, and add light to the knowledge.',
            9: 'Born: Born is to bring into existence a mental birth of self.',
            0: 'Cipher'
        }
    }
});
