define([], function() {
    return {
        alpha: {
            A: 'Allah',
            B: 'Be or Born',
            C: 'Cee (See)',
            D: 'Divine',
            E: 'Equality',
            F: 'Father',
            G: 'God',
            H: 'He or Her',
            I: 'I or Islam',
            J: 'Justice',
            K: 'King or Kingdom',
            L: 'Love, Hell or Right',
            M: 'Master',
            N: 'In or Now Nation',
            O: 'Cypher',
            P: 'Power',
            Q: 'Queen',
            R: 'Rule or Ruler',
            S: 'Self or Savior',
            T: 'Truth or Square',
            U: 'You, Universe, and U-N-I-Verse',
            V: 'Victory',
            W: 'Wisdom',
            X: 'Unknown',
            Y: 'Why',
            Z: 'Zig-Zag-Zig'
        },
        numerics: {
            1: 'Knowledge',
            2: 'Wisdom',
            3: 'Understanding',
            4: 'Culture Freedom',
            5: 'Power Refinement',
            6: 'Equality',
            7: 'God',
            8: 'Build Destroy',
            9: 'Born',
            0: 'Cipher'
        },
        alphanumerics: {
            A: 'Allah',
            B: 'Be Born',
            C: 'Cee (See)',
            D: 'Divine',
            E: 'Equality',
            F: 'Father',
            G: 'God',
            H: 'He or Her',
            I: 'I Islam',
            J: 'Justice',
            K: 'King Kingdom',
            L: 'Love Hell Right',
            M: 'Master',
            N: 'In Now Nation',
            O: 'Cypher',
            P: 'Power',
            Q: 'Queen',
            R: 'Rule Ruler',
            S: 'Self Savior',
            T: 'Truth Square',
            U: 'You Universe U N I Verse',
            V: 'Victory',
            W: 'Wisdom',
            X: 'Unknown',
            Y: 'Why',
            Z: 'Zig Zag Zig',
            1: 'Knowledge',
            2: 'Wisdom',
            3: 'Understanding',
            4: 'Culture Freedom',
            5: 'Power Refinement',
            6: 'Equality',
            7: 'God',
            8: 'Build Destroy,
            9: 'Born',
            0: 'Cipher'
        }
    }
});
